$(function(){
    $("#mainTitle").click(function(){
        $("home-layout").toggle();
    });
    $("#mainTitleA").click(function(){
        $("home-layout").toggle();
    });
    $("#mainTitleB").click(function(){
        $("home-layout").toggle();
    });
});
