image: publysher/hugo

#before_script:
#  - apt-get update -qq && apt-get install -y -qq git zsh curl
#  - apt-get update -qq
#  - curl -sL https://deb.nodesource.com/setup_6.x | bash -
#  - apt-get install -y nodejs
#  - curl -L https://npmjs.org/install.sh | sh 
pages:
  script:
  - hugo version
  - hugo
    #  - npm i html-minifier
    #  - ./bin/html-minifier.sh
  artifacts:
    paths:
    - public
  only:
  - master

#deploy:
#  script:
#  - git config --global user.email "syui@users.noreply.github.com"
#  - git config --global user.name "syui"
#  - cd ./bin
#  - ./comment-touch.sh
#  - cd ../syui.gitlab.io-comment
#  - git push https://${GITHUB_API_TOKEN}@github.com/mba-hack/syui.gitlab.io-comment.git
