baseurl = "https://syui.cf"
languageCode = "ja-jp"
title = "syui.cf"
copyright = "&copy; 2019. All rights reserved."
#canonifyurls = true
paginate = 10000

[permalinks]
    post = "/archive/note/:slug"
    blog = "/blog/post/:year/:month/:day/:slug"
    novel = "/novel/yui/:slug"
    app = "/app/dev/:filename"

[author]
	name = "syui"
[params]
    date_format = "2006-01-02"
    mainSections = ["post"]

[markup.goldmark.renderer]
  unsafe = true

[frontmatter]
date  = [":filename", ":default"]
#date  = [":default"]
