name: github pages

on:
  push:
    branches:
    - src
  workflow_run:
    workflows: 
      - push webp
    branches: src
    types:
      - "completed"

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12
        ref: src
        submodules: true
        fetch-depth: 0
    - run: yarn install

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version:
        # extended: true

    - name: Build
      env: 
        TZ: "Asia/Tokyo"
      run: |
           rm -r ./static/manga/build.js*
           echo VUE_APP_PAGE=`ls ./static/manga/*.png|wc -l` > .env
           yarn build
           cp -rf ./dist/*.js ./static/manga
           cp -rf ./dist/*.css ./static/manga
           cp -rf ./dist/*.map ./static/manga

           #touch ./src-manga-en/.env
           #rm -r ./src-manga-en/.env
           #touch ./static/manga/en/build.js*
           #rm -r ./static/manga/en/build.js*
           #echo VUE_APP_PAGE=`ls ./static/manga/en/*.png|wc -l` >> ./src-manga-en/.env
           #cd ./src-manga-en
           #yarn install 
           #yarn build
           #cp -rf ./dist/*.js ../static/manga/en/
           #cp -rf ./dist/*.css ../static/manga/en/
           #cp -rf ./dist/*.map ../static/manga/en/
           #cd ../

           touch ./src-imgauto/.env
           rm -r ./src-imgauto/.env
           echo VUE_APP_IMGNUMBER=`ls ./static/img/yui_*.png|wc -l` >> ./src-imgauto/.env
           echo VUE_APP_IMGNUMBERA=`ls ./static/img/ai_*.png|wc -l` >> ./src-imgauto/.env
           echo VUE_APP_IMGNUMBERC=`ls ./static/img/c_*.png|wc -l` >> ./src-imgauto/.env
           echo VUE_APP_IMGNUMBERO=`ls ./static/img/octo_*.png|wc -l` >> ./src-imgauto/.env
           echo VUE_APP_IMGNUMBERI=`ls ./static/img/item_*.png|wc -l` >> ./src-imgauto/.env
           echo VUE_APP_IMGNUMBERF=`ls ./static/img/f_*.png|wc -l` >> ./src-imgauto/.env
           cd ./src-imgauto
           yarn install 
           yarn build
           cp -rf ./dist/*.js ../static/imgauto
           cp -rf ./dist/*.map ../static/imgauto
           cd ../

           cp -rf ./static/json/img.json ./src-imgdiff/static/json/img.json
           cat ./src-imgdiff/static/json/img.json |jq .
           cd ./src-imgdiff
           yarn install 
           yarn build
           cp -rf ./dist/*.js ../static/imgdiff
           cp -rf ./dist/*.map ../static/imgdiff
           cd ../

           hugo version
           TZ=Asia/Tokyo hugo
           touch ./public/.nojekyll
           cp ./CNAME ./public/

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        publish_branch: master
