name: github pages

on:
  push:
    branches:
    - src
  workflow_run:
    workflows: [push webp]
    types:
      - "completed"

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12
        ref: src
        submodules: true
        fetch-depth: 0
    - run: yarn install

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 0.89.4
        # extended: true

    - name: Build
      env: 
        TZ: "Asia/Tokyo"
      run: |
           hugo version
           TZ=Asia/Tokyo hugo
           touch ./public/.nojekyll
           cp ./CNAME ./public/

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        publish_branch: master
