name: github pages

on:
  push:
    branches:
    - src
  schedule:
  - cron: "00 9 * * *"

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: 12
        ref: src
        submodules: true
        fetch-depth: 0
    - run: yarn install

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version:
        # extended: true

    - name: Build
      env: 
        TZ: "Asia/Tokyo"
      run: |
           rm -r ./static/manga/build.js*
           echo VUE_APP_PAGE=`ls ./static/manga/*.png|wc -l` > .env
           yarn build
           cp -rf ./dist/*.js ./static/manga
           cp -rf ./dist/*.css ./static/manga
           cp -rf ./dist/*.map ./static/manga

           touch ./src-imgauto/.env
           rm -r ./src-imgauto/.env
           echo VUE_APP_IMGNUMBER=`ls ./static/img/yui_*.png|wc -l` > ./src-imgauto/.env
           cd ./src-imgauto
           yarn install 
           yarn build
           cp -rf ./dist/*.js ../static/imgauto
           cp -rf ./dist/*.css ../static/imgauto
           cp -rf ./dist/*.map ../static/imgauto
           cd ../

           hugo version
           TZ=Asia/Tokyo hugo
           touch ./public/.nojekyll
           cp ./CNAME ./public/

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        publish_branch: master
