name: github pages cron
on:
  schedule:
    - cron:  '0 0 * * *'
  push:
    branches:
    - src

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 0
    - name: install squoosh zsh
      env:
        WORKFLOW_FILE_PATH: ${{ github.workflow }}
        GITHUB_REPOSITORY: ${{ github.repository }}
      run: |
        npm i -g @squoosh/cli
        sudo apt-get install -y -qq zsh curl imagemagick rsync jq
    - name: setup hugo
      uses: peaceiris/actions-hugo@v2
    - name: build
      run: |
           w=`cat ./static/json/tarot.json|jq length`
           w=`expr $w + 1`
           e=`ls ./content/ai/tarot/*.gif|wc -l`
           if [ $e -eq $w ];then
           echo ok
           exit
           fi
           ./src-tarot/convert.zsh -a
           hugo
           touch ./public/.nojekyll
           cp ./CNAME ./public/
           git config --local user.email "action@github.com"
           git config --local user.name "GitHub Action"
           if [ -z "`git status -s`" ];then
           exit
           fi
           git pull
           git add .
           git commit -m "push tarot"
    - name: push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: src
    - name: deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        publish_branch: master
