name: push imgdiff

on:
  push:
    branches:
    - src

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: convert json
      run: |
        s=`git --no-pager log --since=1.weeks --name-status |grep -e "A\t" -e "M\t" |grep "static/img/"|grep "\.png"|cut -d / -f 3|sort|uniq`
        echo "$s"
        if [ -z "$s" ];then
        exit
        fi
        rm ./static/json/img.json
        echo '[]' >> ./static/json/img.json
        n=`echo "$s"|wc -l`
        for ((i=1;i<=$n;i++))
        do
        t=`echo "$s"|awk "NR==$i"`
        cat ./static/json/img.json|jq ".+[{\"id\":\"$i\",\"file\": \"/img/$t\"}]"
        cat ./static/json/img.json|jq ".+[{\"id\":\"$i\",\"file\": \"/img/$t\"}]" >> ./static/json/img.tmp
        mv ./static/json/img.tmp ./static/json/img.json
        done
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        if [ -z "`git status -s`" ];then
        exit
        fi
        git add ./static/json/img.json
        git commit -m "push imgdiff"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: src

