name: push webp

on:
  workflow_run:
    workflows: 
      - push imgdiff
    branches: src
    types:
      - "completed"
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 0

    - name: install squoosh
      env:
        WORKFLOW_FILE_PATH: ${{ github.workflow }}
        GITHUB_REPOSITORY: ${{ github.repository }}

      run: |
        npm i -g @squoosh/cli

    - name: convert webp
      run: |
        git pull https://github.com/syui/syui.github.io.git src
        # git --no-pager log -n 3 --name-status|grep "static/img"|grep "\.png"|cut -d / -f 3|sort|uniq
        # s=`git --no-pager log -n 3 --name-status|grep "static/img"|grep "\.png"|cut -d / -f 3|sort|uniq`
        git --no-pager log --since="1 days" --name-status |grep "static/img/"|grep "\.png"|grep yui|cut -d / -f 3|sort|uniq
        s=`git --no-pager log --since="1 days" --name-status |grep "static/img/"|grep "\.png"grep yui|cut -d / -f 3|sort|uniq`
        echo "$s"
        if [ -z "$s" ];then
        exit
        fi
        n=`echo "$s"|wc -l`
        for ((i=1;i<=$n;i++))
        do
        t=`echo "$s"|awk "NR==$i"`
        if [ ! -f ./static/img/$t ];then
        squoosh-cli --webp '{"quality":100}' -d ./static/img/min --resize '{width:600,height:800}' ./static/img/$t
        fi
        done
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        if [ -z "`git status -s`" ];then
        exit
        fi
        git add ./static/img/min
        git commit -m "push webp"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: src

