name: push github contribution json

on:
  schedule:
    - cron:  '00 00 * * 0'
on:
  push:
    branches:
    - src

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install jq
      env:
        WORKFLOW_FILE_PATH: ${{ github.workflow }}
        GITHUB_REPOSITORY: ${{ github.repository }}

      run: |
        sudo apt-get install -y jq curl

    - name: get json
      run: |
        curl -sL https://github-contributions-api.deno.dev/syui.json|jq ".|del(.totalContributions)|.[]|.[]|.[]|{(.date+\"T00:00:00Z\"|fromdate|tostring):(.contributionCount)}"|jq -n '[inputs] | add' >> ./static/json/cal.json.tmp
        mv ./static/json/cal.json.tmp ./static/json/cal.json
        cat ./static/json/cal.json|jq .
        git add ./static/json/cal.json
        git commit -m "push webp"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: src

